name: Mark succeeded with issues AZDO jobs as neutral 
on:
  check_run:
    types: [completed]
permissions:
  checks: write
jobs:
  update-checks:
    name: Update checks
    runs-on: ubuntu-latest
    steps:
      - name: run pwsh
        shell: pwsh
        run: |
          # dir env:
          $commitId=$env:GITHUB_SHA
          Write-Host "Commit ID: $commitId"

          $repoName=$env:GITHUB_REPOSITORY
          Write-Host "Repo Name: $repoName"
          
          $uri = "https://api.github.com/repos/$($repoName)/commits/$($commitId)/check-runs"
          Write-Host "URI: $uri"
          $headers = @{ "Accept" = "application/vnd.github+json"; "X-GitHub-Api-Version" = "2022-11-28" }
          $response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get
          
          # find the check runs which output title matches "succeeded with issues"
          foreach ($checkRun in $response.check_runs) {
            $checkRunId = $checkRun.id
            Write-Host "Check Run ID: $checkRunId"
            
            Write-Host "Marking check run $($checkRunId) as neutral"
            $body = @{
              "conclusion" = "neutral"             
            }
            $bodyJson = $body | ConvertTo-Json -Depth 100
            $headers = @{ "Accept" = "application/vnd.github+json"; "X-GitHub-Api-Version" = "2022-11-28"; "Authorization" = "Bearer " + "${{ secrets.GITHUB_TOKEN }}" }
            $uri = "https://api.github.com/repos/$($repoName)/check-runs/$($checkRunId)"
            $response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Patch -Body $bodyJson
          }